import os
import pandas as pd
import numpy as np
import json
import itertools
from datetime import datetime

# ANSI Colors
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
MAGENTA = "\033[95m"
RESET = "\033[0m"

# Path to the performance logs generated by your master/stress tests
LOG_PATH = "core/data/morning_history.json" 

class M9Optimizer:
    """
    Model 9 Optimizer: The Meta-Strategist.
    Finds the optimal 'Regime Weights' for the Portfolio Controller.
    """
    def __init__(self):
        self.regimes = ["BULL", "BEAR", "SIDEWAYS"]
        self.models = ["M1", "M2", "M3", "M4", "M6", "M7", "M8"]

    def load_model_performance(self):
        """
        In a production environment, this would load real trade history.
        For this optimizer, we simulate the performance matrix based on our 
        previous training audits.
        """
        # Format: {Regime: {Model: [List of Returns]}}
        performance_matrix = {
            "BULL": {
                "M1": [1.8, 2.5, -3.0, 4.0, 1.2],
                "M3": [5.2, -3.5, 6.1, 8.0, -3.5],
                "M4": [3.1, 4.5, 2.2, 5.0, -1.5],
                "M6": [0.5, 1.2, -0.8, 2.1, 0.4]
            },
            "BEAR": {
                "M2": [7.8, -5.0, 8.5, 12.0, 6.4],
                "M1": [4.1, -4.0, 3.8, 5.2, -4.0],
                "M7": [3.5, 4.2, -3.0, 5.5, 6.0]
            },
            "SIDEWAYS": {
                "M1": [2.2, -3.0, 1.5, 2.8, -1.0],
                "M4": [2.4, 3.1, -2.0, 1.8, 2.5],
                "M8": [1.2, 0.8, 1.5, -0.5, 1.1]
            }
        }
        return performance_matrix

    def calculate_kelly_weight(self, returns):
        """Calculates a simplified Kelly Criterion weight for a model."""
        if not returns: return 0.0
        wins = [x for x in returns if x > 0]
        losses = [x for x in returns if x <= 0]
        
        win_rate = len(wins) / len(returns)
        avg_win = np.mean(wins) if wins else 0
        avg_loss = abs(np.mean(losses)) if losses else 1.0 # Avoid DivZero
        
        # Kelly % = (W/L_ratio * win_rate - loss_rate) / W/L_ratio
        win_loss_ratio = avg_win / avg_loss
        kelly = (win_loss_ratio * win_rate - (1 - win_rate)) / win_loss_ratio
        
        return max(0, min(kelly, 1.0)) # Clamp between 0 and 1

    def optimize_regime(self, regime, data):
        print(f"\n{CYAN}🛠️ Optimizing Weights for Regime: {regime}{RESET}")
        print("─"*60)
        
        results = {}
        for model, returns in data.items():
            k_weight = self.calculate_kelly_weight(returns)
            ev = np.mean(returns)
            results[model] = {"kelly": k_weight, "ev": ev}
            print(f" {model:<10} | EV: {ev:>+6.2f}% | Suggested Weight: {k_weight:.2f}")
            
        # Normalize weights so they sum to 1.0 or remain relative
        total_k = sum([v['kelly'] for v in results.values()])
        if total_k > 0:
            for m in results:
                results[m]['normalized'] = results[m]['kelly'] / total_k
        
        return results

    def run(self):
        print(f"\n{MAGENTA}🚀 WINTRA MODEL 9: META-WEIGHT OPTIMIZATION{RESET}")
        raw_data = self.load_model_performance()
        
        final_config = {}
        for regime in self.regimes:
            if regime in raw_data:
                final_config[regime] = self.optimize_regime(regime, raw_data[regime])
        
        print(f"\n{GREEN}🏆 OPTIMIZED M9 REGIME MATRIX{RESET}")
        print("─"*60)
        for regime, models in final_config.items():
            print(f"\n[{regime}] Priority List:")
            sorted_m = sorted(models.items(), key=lambda x: x[1]['kelly'], reverse=True)
            for m, stats in sorted_m:
                print(f"  - {m:<12}: {stats['kelly']:.2f}")
                
        self.generate_m9_config(final_config)

    def generate_m9_config(self, config):
        """Outputs the new REGIME_PRIORITY block for Model 9."""
        print(f"\n{YELLOW}📝 COPY THIS INTO core/models/m9_controller.py:{RESET}")
        print("─"*60)
        print("REGIME_PRIORITY = {")
        for regime, models in config.items():
            print(f"    \"{regime}\": {{")
            for m, stats in models.items():
                print(f"        \"{m}\": {stats['kelly']:.2f},")
            print("    },")
        print("}")
        print("─"*60)

if __name__ == "__main__":
    opt = M9Optimizer()
    opt.run()
